### ISSUE TITLE
Cannot assign to read only property 'persistent' of true

### ISSUE THREAD

**Issue by hyusetiawan** [techfort/LokiJS#195]
creating a dynamic view and passing the true flag for it to be persistent causes that error
`
var alert1 = series.addDynamicView('alert1', true)
`

stack trace: 
`
/Users/Projects/hardbeat/node_modules/lokijs/src/lokijs.js:2004
        this.options.persistent = false;
                                ^
TypeError: Cannot assign to read only property 'persistent' of true
    at LokiEventEmitter.DynamicView (/Users/Projects/hardbeat/node_modules/lokijs/src/lokijs.js:2004:33)
    at LokiEventEmitter.Collection.addDynamicView (/Users/Projects/hardbeat/node_modules/lokijs/src/lokijs.js:2889:16)
    at Object.<anonymous> (/Users/Projects/hardbeat/tests/alert.js:12:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/.nvm/versions/node/v0.12.7/lib/node_modules/nodeunit/lib/nodeunit.js:75:37
`

**Comment by obeliskos** [comment]
Right, I believe I had to expand that param out into an 'options' param which can possibly contain : 
```javascript
var dv = coll.addDynamicView('test', { 
  persistent: true, 
  sortPriority: 'passive' 
});
```

Can you try using { persistent: true } and let me know if that works.

**Comment by techfort** [comment]
@hyusetiawan have you had any luck with this? if @obeliskos 's fix worked i will close, or else let me know.

**Comment by hyusetiawan** [comment]
@techfort @obeliskos :
it does work, im closing the issue
