### ISSUE TITLE
addDynamicView(name, persistent = true) fails

### ISSUE THREAD

**Issue by moshewe** [techfort/LokiJS#287]
In the docs it says addDynamicView can be passed an optional boolean argument. I get this when running said line:

```
TypeError: Cannot assign to read only property 'persistent' of true
    at LokiEventEmitter.DynamicView (c:\Exposebox\Source\ad-net-bidder\src\node_modules\lokijs\src\lokijs.js:2156:33)
    at LokiEventEmitter.Collection.addDynamicView (c:\Exposebox\Source\ad-net-bidder\src\node_modules\lokijs\src\lokijs.js:3093:16)
```

passing an options _object_ works:
`collection.addDynamicView(name, {persistent: true})`

I guess this is a mistake in the docs by looking at the source code...

**Comment by obeliskos** [comment]
Related to issue #195 and #266 

Assigning to techfort to update lokijs.org

**Comment by obeliskos** [comment]
our live jsdocs linked in wiki are best source reference so closing, thanks
