### ISSUE TITLE
Installing problem with npm to Angular 2 CLI project

### ISSUE THREAD

**Issue by Mithgroth** [techfort/LokiJS#487]
Any instructions for using Loki with Angular 2 CLI projects?
I seem to have some trouble installing it with npm.

```
$ npm install lokijs

> node-zopfli@1.4.0 install E:\Emek\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (E:\Emek\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at E:\Emek\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at E:\Emek\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "E:\\Emek\nodejs\\node.exe" "E:\\Emek\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\Emek\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=E:\\Emek\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd E:\Emek\node_modules\node-zopfli
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'E:\Emek\nodejs\node.exe E:\Emek\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\Emek\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\Emek\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Emek\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "E:\\Emek\\nodejs\\node.exe" "E:\\Emek\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\Emek\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'E:\Emek\nodejs\node.exe E:\Emek\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\Emek\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\Emek\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
outdrafted!@0.0.0 E:\Emek\
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0
`-- lokijs@1.4.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN @angular/platform-server@2.0.2 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN @angular/platform-server@2.0.2 requires a peer of @angular/common@2.0.2 but none was installed.
npm WARN @angular/platform-server@2.0.2 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/platform-server@2.0.2 requires a peer of @angular/platform-browser@2.0.2 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 (node_modules\node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by Kanaye** [comment]
Hi @Mithgroth!

It doesn't look like coming from the lokijs npm package, because lokijs has no dependencies and npm is failing to install `node-zopfli`.

You can try to install it to an empty ptoject (without other packages).

**Comment by Mithgroth** [comment]
It seems that Loki has been installed under node_modules, however I have no idea what the error is about. Thanks anyways!
