### ISSUE TITLE
Unhandled Promise rejection: No available storage method found.

### ISSUE THREAD

**Issue by riksof-abdulrauf** [techfort/LokiJS#541]
Facing error after adding lokijs with the help of 
https://www.npmjs.com/package/angular2-loki

   Unhandled Promise rejection: No available storage method found. ; Zone: <root> ; Task: Promise.then ; Value: Error: No available storage method found.
    at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/localforage/dist/localforage.js:2247:25
    at ZoneDelegate.invoke (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:232:26)
    at Zone.run (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:114:43)
    at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:502:57
    at ZoneDelegate.invokeTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:265:35)
    at Zone.runTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:154:47)
    at drainMicroTaskQueue (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:401:35)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) Error: No available storage method found.
    at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/localforage/dist/localforage.js:2247:25
    at ZoneDelegate.invoke (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:232:26)
    at Zone.run (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:114:43)
    at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:502:57
    at ZoneDelegate.invokeTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:265:35)
    at Zone.runTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:154:47)
    at drainMicroTaskQueue (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:401:35)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
{ Error: Uncaught (in promise): Error: No available storage method found.
Error: No available storage method found.
    at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/localforage/dist/localforage.js:2247:25
    at ZoneDelegate.invoke (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:232:26)
    at Zone.run (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:114:43)
    at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:502:57
    at ZoneDelegate.invokeTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:265:35)
    at Zone.runTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:154:47)
    at drainMicroTaskQueue (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:401:35)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at resolvePromise (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:468:31)
    at resolvePromise (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:453:17)
    at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:502:17
    at ZoneDelegate.invokeTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:265:35)
    at Zone.runTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:154:47)
    at drainMicroTaskQueue (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:401:35)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
  rejection: 
   Error: No available storage method found.
       at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/localforage/dist/localforage.js:2247:25
       at ZoneDelegate.invoke (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:232:26)
       at Zone.run (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:114:43)
       at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:502:57
       at ZoneDelegate.invokeTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:265:35)
       at Zone.runTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:154:47)
       at drainMicroTaskQueue (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:401:35)
       at runMicrotasksCallback (internal/process/next_tick.js:58:5)
       at _combinedTickCallback (internal/process/next_tick.js:67:7)
       at process._tickCallback (internal/process/next_tick.js:98:9),
  promise: 
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: 
      Error: No available storage method found.
          at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/localforage/dist/localforage.js:2247:25
          at ZoneDelegate.invoke (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:232:26)
          at Zone.run (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:114:43)
          at /Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:502:57
          at ZoneDelegate.invokeTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:265:35)
          at Zone.runTask (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:154:47)
          at drainMicroTaskQueue (/Users/riksof/Documents/myproject/myproject-angular2/node_modules/zone.js/dist/zone-node.js:401:35)
          at runMicrotasksCallback (internal/process/next_tick.js:58:5)
          at _combinedTickCallback (internal/process/next_tick.js:67:7)
          at process._tickCallback (internal/process/next_tick.js:98:9) },
  zone: 
   Zone {
     _properties: {},
     _parent: null,
     _name: '<root>',
     _zoneDelegate: 
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: null,
        _forkZS: null,
        _forkDlgt: null,
        _interceptZS: null,
        _interceptDlgt: null,
        _invokeZS: null,
        _invokeDlgt: null,
        _handleErrorZS: null,
        _handleErrorDlgt: null,
        _scheduleTaskZS: null,
        _scheduleTaskDlgt: null,
        _invokeTaskZS: null,
        _invokeTaskDlgt: null,
        _cancelTaskZS: null,
        _cancelTaskDlgt: null,
        _hasTaskZS: null,
        _hasTaskDlgt: null } },
  task: 
   ZoneTask {
     runCount: 1,
     type: 'microTask',
     zone: 
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }

**Comment by Viatorus** [comment]
I would say, the adapter angular2-loki is not maintained by use. But it would be good if we have one official.
