### ISSUE TITLE
Can't load empty JSON file.

### ISSUE THREAD

**Issue by xbenjii** [techfort/LokiJS#58]
I'm using the following code in node-webkit/angular:

```
app.service('Database', [
    function() {
        return function(dbName) {

            var self = this;

            this.initialized = false;
            this.db = new loki(dbName + '.json', {
                env: 'NODEJS',
                autoload: true
            });
            this.models = {};

            this.init = function(collections, callback) {
                if (fs.existsSync(dbName + '.json')) {
                    this.db.loadDatabase({}, function() {
                        initDb();
                    });
                } else {
                    initDb();
                }

                function initDb() {
                    collections.forEach(function(collection) {
                        self.db.addCollection(collection);
                        self.models[collection] = self.db.getCollection(collection);
                    });
                    self.initialized = true;
                    callback();
                }
            };

            this.save = function(callback) {
                self.db.saveDatabase(callback);
            };

            return this;
        };
    }
]);
```

This worked in 1.0, bar the API changes I've made for 1.1. It would load an empty database which would then allow it to save if it hadn't been created, now it just throws an error because it's trying to parse JSON that doesn't exist.

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at LokiEventEmitter.Loki.loadJSON (C:\njs\arch\node_modules\lokijs\src\lokijs.js:396:22)
    at readFileCallback (C:\njs\arch\node_modules\lokijs\src\lokijs.js:677:16)
    at fs.js:289:14
    at Object.oncomplete (fs.js:97:15)
```

Edit: Your desktop_app demo throws the same error. Also if there's no file present, it throws an ENOENT error. Instead, it should probably create the file and initialize a database.

**Comment by xbenjii** [comment]
Closing for now.
