### ISSUE TITLE
Typescript: autoloadCallback zone error when passing a class method

### ISSUE THREAD

**Issue by cgebe** [techfort/LokiJS#604]
I have the following service:

```
import * as Loki from 'lokijs';

@Injectable()
export class LokiDatabaseService extends Database {

    private static readonly DATABASE = "test.db";
    private database: any;

    constructor() {
        super();
        this.database = new Loki(LokiDatabaseService.DATABASE, { autoload: true, autoloadCallback: this.init });
    }

    public init(): void {
        let keys = this.database.getCollection('keys');
        if (!keys) {
            this.database.addCollection('keys');
        }

        this.database.saveDatabase();
    }
}
```

When instantiate the service i get the following error:

```
/node_modules/zone.js/dist/zone-node.js:195
                        throw error;
                        ^

TypeError: Cannot read property 'database' of undefined
    at LokiDatabaseService.init (app/lib/services/lokiDatabase.service.js:1:14292)
    at node_modules/lokijs/src/lokijs.js:2442:15
    at loadDatabaseCallback (node_modules/lokijs/src/lokijs.js:2371:15)
    at readFileCallback (node_modules/lokijs/src/lokijs.js:2177:15)
    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone-node.js:424:31)
    at Zone.runTask (node_modules/zone.js/dist/zone-node.js:191:47)
    at ZoneTask.invokeTask (node_modules/zone.js/dist/zone-node.js:498:34)
    at ZoneTask.invoke (node_modules/zone.js/dist/zone-node.js:487:48)
    at data.args.(anonymous function) (node_modules/zone.js/dist/zone-node.js:1041:25)
    at tryToString (fs.js:447:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:434:12)
```

Edit: The init method is actually called, when i insert a console.log()

**Comment by Kanaye** [comment]
Hi @cgebe!
The bug is not in Lokijs but in your code.
You are passing a function without binding it to the right `this` to init, unfortunatly typescript doesn't prevent this kind of error.
You can fix this by either `bind()`-ing it or by using an arrow function.

Examples:
Arrow function:
```javascript
this.database = new Loki(LokiDatabaseService.DATABASE, { 
    autoload: true, 
    autoloadCallback: () => this.init() 
});
```
Bind:
```javascript
this.database = new Loki(LokiDatabaseService.DATABASE, { 
    autoload: true, 
    autoloadCallback: this.init.bind(this) 
});
```

**Comment by cgebe** [comment]
Thank you, missed that ;)
