### ISSUE TITLE
findAndRemove does not update collection.constraints.unique

### ISSUE THREAD

**Issue by metromorph** [techfort/LokiJS#677]
Hi,

I think we discovered a bug introduced in 1.5.4. Probably introduced during
the fix of [#663](https://github.com/techfort/LokiJS/issues/663)

The following code works in 1.5.3 but not in the latest release:

```
const data = [
    {name:'Sleipnir', legs: 8},
    {name:'Jormungandr', legs: 0},
    {name:'Hel', legs: 2}
];

const loki = require("lokijs");
const _ = require("lodash");

const db = new loki("test.json");
const collection = db.addCollection("children", {
    unique: ["name"]
});

data.forEach(function(c) {
        collection.insert(_.cloneDeep(c));
});
collection.findAndRemove();
//console.log(collection.constraints.unique);  

collection.insert(_.cloneDeep(data[0])); // throws Duplicate key for property name: Sleipnir
```

Error Message is

```
/home/nikolas/work/incubation/lokijs/node_modules/lokijs/src/lokijs.js:5870
        throw (err); // re-throw error so user does not think it succeeded
        ^

Error: Duplicate key for property name: Sleipnir
    at UniqueIndex.set
(/home/nikolas/work/incubation/lokijs/node_modules/lokijs/src/lokijs.js:7161:17)
    at Collection.add
(/home/nikolas/work/incubation/lokijs/node_modules/lokijs/src/lokijs.js:5832:31)
    at Collection.insertOne
(/home/nikolas/work/incubation/lokijs/node_modules/lokijs/src/lokijs.js:5600:17)
    at Collection.insert
(/home/nikolas/work/incubation/lokijs/node_modules/lokijs/src/lokijs.js:5539:21)
    at Object.<anonymous>
(/home/nikolas/work/incubation/lokijs/index.js:27:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Reason seems to be the uncleaned constraints.unique in collection:

Console log from above is

```
{ name:
   UniqueIndex {
     field: 'name',
     keyMap: { Sleipnir: undefined, Jormungandr: undefined, Hel:
undefined },
     lokiMap: { '1': undefined, '2': undefined, '3': undefined } } }
```

in 1.5.3, but

```
{ name:
   UniqueIndex {
     field: 'name',
     keyMap: { Sleipnir: [Object], Jormungandr: [Object], Hel: [Object] },
     lokiMap: { '1': 'Sleipnir', '2': 'Jormungandr', '3': 'Hel' } } }
```

in 1.5.4.

Best Regards,
Niko

**Comment by xhawk18** [comment]
yes, i meet the same problem. 1.5.3 is OK, but 1.5.4 failed.

**Comment by metromorph** [comment]
Great! With this commit our code works fine again!

Thanks for the fast fix.

**Comment by TameBadger** [comment]
@obeliskos Heyo, just wondering, when would this fix go into a new release ?

**Comment by obeliskos** [comment]
LokiJS version 1.5.5 has published by @techfort and it includes this fix.

**Comment by metromorph** [comment]
@obeliskos @techfort Thanks for your work!
