### ISSUE TITLE
Converting circular structure to JSON error

### ISSUE THREAD

**Issue by MoonlightCapital** [techfort/LokiJS#783]
I am not sure of why this happens, but sometimes, when I try to update a document, this error appears, and the whole script crashes:

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Loki.serialize (/rbd/pnpm-volume/54ffc3b6-09d9-4409-ae00-01e113ce1d36/node_modules/.registry.npmjs.org/lokijs/1.5.6/node_modules/lokijs/src/lokijs.js:1254:36)
    at Loki.saveDatabaseInternal (/rbd/pnpm-volume/54ffc3b6-09d9-4409-ae00-01e113ce1d36/node_modules/.registry.npmjs.org/lokijs/1.5.6/node_modules/lokijs/src/lokijs.js:2645:68)
    at Loki.saveDatabase (/rbd/pnpm-volume/54ffc3b6-09d9-4409-ae00-01e113ce1d36/node_modules/.registry.npmjs.org/lokijs/1.5.6/node_modules/lokijs/src/lokijs.js:2690:12)
    at Timeout.autosaveHandleInterval [as _onTimeout] (/rbd/pnpm-volume/54ffc3b6-09d9-4409-ae00-01e113ce1d36/node_modules/.registry.npmjs.org/lokijs/1.5.6/node_modules/lokijs/src/lokijs.js:2791:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

I am unsure of why this happens, since the error tells me nothing useful. Any idea?

```js
message.author.data.points -= 2
      console.log(message.author.data)
      client.db.updateUser(message.author.data)```

The console.log shows the following:
```

```
{ id: '256460316660072448',
  powerlevel: 10,
  blacklistReason: null,
  cardColor: '#008080',
  points: 320,
  createdAt: '2018-11-28T06:23:44.286Z',
  updatedAt: '2018-11-28T13:10:08.482Z',
  meta:
   { revision: 2,
     created: 1559308426928,
     version: 0,
     updated: 1560192286623 },
  '$loki': 1 }
```

And this is the updateUser function:

```js
async function updateUser(data) {
  db.users.update(data)

  const update = await getUserFresh(data.id)
  console.log(update)

  await cacheUser(update)

  return update
}```

**Comment by erik-helmers** [comment]
It's probably not a LokiJS fault.

The JSON parse error means that you're trying to save an object which as a circular dependencies.. You did something like
    let a = {b: 1, c:2}
    a.a = a
    collection.insert(a);l
