### ISSUE TITLE
Cannot generate JSDoc.

### ISSUE THREAD

**Issue by metaa** [techfort/LokiJS#818]
In `package.json` we got a script named `jsdoc`.
```js
"jsdoc": "./node_modules/.bin/jsdoc -c jsdoc-conf.json",
```
Despite its existence, the configuration file `jsdoc-conf.json` does not exist in the repository.

**Comment by metaa** [comment]
It seems to have been renamed in [this commit](../commit/bef07bfb1e9e5048f4343db0097f8492926092be).

**Comment by metaa** [comment]
It seems to have been renamed in [this commit](../commit/bef07bfb1e9e5048f4343db0097f8492926092be), but simply updating its name in the script yields a TypeError in a subdependency called "[requizzle](https://www.npmjs.com/package/requizzle)"

```
D:\JS\projects\forks\LokiJS>npm run jsdoc

> lokijs@1.5.8 jsdoc D:\JS\projects\forks\LokiJS
> jsdoc -c docs-conf.json

D:\JS\projects\forks\LokiJS\node_modules\requizzle\lib\requizzle.js:45
        if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
                       ^

TypeError: Cannot read property '0' of null
    at isNativeModule (D:\JS\projects\forks\LokiJS\node_modules\requizzle\lib\requizzle.js:45:17)
    at Requizzle.requizzle (D:\JS\projects\forks\LokiJS\node_modules\requizzle\lib\requizzle.js:82:6)
    at infectProxy (D:\JS\projects\forks\LokiJS\node_modules\requizzle\lib\loader.js:82:28)
    at Module.targetModule.require (D:\JS\projects\forks\LokiJS\node_modules\requizzle\lib\loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\JS\projects\forks\LokiJS\node_modules\jsdoc\lib\jsdoc\fs.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Object.load (D:\JS\projects\forks\LokiJS\node_modules\requizzle\lib\loader.js:112:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lokijs@1.5.8 jsdoc: `jsdoc -c docs-conf.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lokijs@1.5.8 jsdoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Metaa\AppData\Roaming\npm-cache\_logs\2019-11-09T02_57_10_500Z-debug.log
```

This is the log it created:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Metaa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'jsdoc'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.3.1
4 verbose run-script [ 'prejsdoc', 'jsdoc', 'postjsdoc' ]
5 info lifecycle lokijs@1.5.8~prejsdoc: lokijs@1.5.8
6 info lifecycle lokijs@1.5.8~jsdoc: lokijs@1.5.8
7 verbose lifecycle lokijs@1.5.8~jsdoc: unsafe-perm in lifecycle true
8 verbose lifecycle lokijs@1.5.8~jsdoc: PATH: C:\Users\Metaa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\JS\projects\forks\LokiJS\node_modules\.bin;D:\JS\projects\forks\LokiJS\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Users\Metaa\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\Metaa\AppData\Local\Microsoft\WindowsApps;C:\Users\Metaa\AppData\Roaming\npm;C:\Users\Metaa\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle lokijs@1.5.8~jsdoc: CWD: D:\JS\projects\forks\LokiJS
10 silly lifecycle lokijs@1.5.8~jsdoc: Args: [ '/d /s /c', 'jsdoc -c docs-conf.json' ]
11 silly lifecycle lokijs@1.5.8~jsdoc: Returned: code: 1  signal: null
12 info lifecycle lokijs@1.5.8~jsdoc: Failed to exec jsdoc script
13 verbose stack Error: lokijs@1.5.8 jsdoc: `jsdoc -c docs-conf.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Metaa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Metaa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid lokijs@1.5.8
15 verbose cwd D:\JS\projects\forks\LokiJS
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Metaa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "jsdoc"
18 verbose node v12.3.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error lokijs@1.5.8 jsdoc: `jsdoc -c docs-conf.json`
22 error Exit status 1
23 error Failed at the lokijs@1.5.8 jsdoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
