### ISSUE TITLE
TypeError: b.indexOf is not a function

### ISSUE THREAD

**Issue by darrylmorley** [techfort/LokiJS#832]
Hi,

I'm using Gridsome which is failing to build due to an error with lokijs. I'm hoping that I might be able to get some help or advice here?
The error is:
```
TypeError: b.indexOf is not a function
    at $in (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/lokijs/src/lokijs.js:503:18)
    at dotSubScan (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/lokijs/src/lokijs.js:393:22)
    at dotSubScan (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/lokijs/src/lokijs.js:396:24)
    at Resultset.find (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/lokijs/src/lokijs.js:3545:19)
    at calcTotalPages (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/gridsome/lib/app/build/createRenderQueue.js:54:32)
    at createRenderQueue (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/gridsome/lib/app/build/createRenderQueue.js:20:28)
    at module.exports (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/gridsome/lib/build.js:24:17)
```

**Comment by darrylmorley** [comment]
This was a graphql query issue.
https://github.com/gridsome/gridsome/issues/1034
